### PR TITLE
Try this

### PR DESCRIPTION
**Pull request by domesticmouse**
It now seems to run, once I got rid of the GMSMapView that was instantiated too early then discarded.

### CODE REVIEW

**Comment by craigpearce5** [comment]
It looks like you moved the api key from didFinishLaunchingWithOptions to applicationDidBecomeActive - do you think that could have been the solution?

**Comment by domesticmouse** [comment]
It doesn't look like it moved to me: https://github.com/domesticmouse/CPMapsAPI/blob/master/DaycareIQ%20Child%20Care%20Locator/AppDelegate.swift

Our belief is that the GMSMapView that is being instantiated on construction of your ViewController then thrown away is the core of your issue. You are effectively using it to declare the type of an attribute, which is kinda bad.

**Comment by craigpearce5** [comment]
Oops. Sorry I misread the git change page, I'm new to github (and
programming in general).

**Comment by domesticmouse** [comment]
The most important thing with programming is to keep trying things out. Sooner or later the patterns will start to click, and you will be able to see larger patterns, and be able to put together larger systems. It just takes time to build the mental models to make it all work. You'll get there =)

**Pull request merged**
